### ISSUE TITLE
feature_request(usage): shortcut

### ISSUE THREAD

**Issue by Kristinita** [kakakikikeke/compact-toolbar#3]
### 1. Summary

It would be nice, if would be possible run compact-toolbar actions via shortcut.

### 2. Example of expected behavior

Currently, that hide folder names in toolbar, I click to compact-toolbar icon in my Firefox Bookmarks Toolbar.

It would be nice, if users can do the same via shortcut.

#### 3.1. Common cause

Automation.

#### 3.2. Details

I'm a streamer. I don't want my users to see the names of my folders, but I want to see them in my daily work, not on streams. So I use compact-toolbar.

I use scripts, that set my stream workplace. For example, I close some programs and open others, for streaming; [**I close all current Firefox tabs**](https://superuser.com/q/1537534/572069) and open tabs, that I need for streams. I perform all these actions by pressing one shortcut.

But I don't know, how I can include toggling folders titles to my automation process. Currently, I need manually click to compact-toolbar button. If compact-toolbar had a hotkey, I could toggle folders titles without any manual actions [**use AutoHotkey**](https://www.autohotkey.com/docs/commands/Send.htm).

#### 4.1. You can automatically click to button coordinates

See [**3.3 item**](https://superuser.com/q/1537534/572069).

But if you know another methods for programmatically clicking to compact-toolbar button, please, tell me about them.

Thanks.

**Comment by kakakikikeke** [comment]
It may be implemented a feature with "commands api" https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands. I'll try to code it.

**Comment by kakakikikeke** [comment]
![new_feature_test](https://user-images.githubusercontent.com/1751050/78514169-f2eea480-77ea-11ea-9f5f-81320a501a05.gif)

How was it ? A shortcut key is defined "Cmd+Shift+Y" on mac.

**Comment by kakakikikeke** [comment]
v1.2.0 status is reviewing...

**Comment by kakakikikeke** [comment]
Released! https://addons.mozilla.org/ja/firefox/addon/compact-toolbar/versions/

**Comment by Kristinita** [comment]
✔️ **Status: Works for me**

Thanks.
